### ISSUE TITLE
ImportError: cannot import name 'runtime_checkable' from 'typing_extensions'

### ISSUE THREAD

**Issue by lakeofsoft** [trailofbits/graphtage#30]
Win10, Python 3.7, after 

>pip3 install graphtage  (went without any issues):

```
PS U:\> graphtage
Traceback (most recent call last):
  File "d:\_bin\miniconda\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\_bin\miniconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\_bin\Miniconda\Scripts\graphtage.exe\__main__.py", line 4, in <module>
  File "d:\_bin\miniconda\lib\site-packages\graphtage\__init__.py", line 1, in <module>
    from . import graphtage
  File "d:\_bin\miniconda\lib\site-packages\graphtage\graphtage.py", line 8, in <module>
    from .edits import AbstractEdit, EditCollection
  File "d:\_bin\miniconda\lib\site-packages\graphtage\edits.py", line 8, in <module>
    from .tree import CompoundEdit, Edit, EditedTreeNode, GraphtageFormatter, TreeNode
  File "d:\_bin\miniconda\lib\site-packages\graphtage\tree.py", line 7, in <module>
    from typing_extensions import Protocol, runtime_checkable
ImportError: cannot import name 'runtime_checkable' from 'typing_extensions' (d:\_bin\miniconda\lib\site-packages\typing_extensions.py)
```
```
typing                            3.6.6
typing-extensions                 3.6.6
```

**Comment by lakeofsoft** [comment]
Upgrading typing-extensions to 3.7.4.3 helped to resolve the issue.

**Comment by ESultanik** [comment]
This is now fixed in `master` and will be included in the next release.
