### ISSUE TITLE
TypeError: Cannot create a consistent method resolution

### ISSUE THREAD

**Issue by TMiguelT** [trailofbits/graphtage#36]
Under Python 3.9, I get the following error when running any graphtage command:

```
Traceback (most recent call last):
  File "/media/michael/Storage2/Programming/CWLDiff/venv/bin/graphtage", line 5, in <module>
    from graphtage.__main__ import main
  File "/media/michael/Storage2/Programming/CWLDiff/venv/lib/python3.9/site-packages/graphtage/__init__.py", line 1, in <module>
    from . import graphtage
  File "/media/michael/Storage2/Programming/CWLDiff/venv/lib/python3.9/site-packages/graphtage/graphtage.py", line 11, in <module>
    from .multiset import MultiSetEdit
  File "/media/michael/Storage2/Programming/CWLDiff/venv/lib/python3.9/site-packages/graphtage/multiset.py", line 12, in <module>
    from .matching import WeightedBipartiteMatcher
  File "/media/michael/Storage2/Programming/CWLDiff/venv/lib/python3.9/site-packages/graphtage/matching.py", line 263, in <module>
    class PathSet(Generic[T], Matching[T]):
  File "/usr/lib/python3.9/abc.py", line 85, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
TypeError: Cannot create a consistent method resolution
order (MRO) for bases Generic, Matching
```

Under Python 3.8 this doesn't seem to exist.

**Comment by ESultanik** [comment]
Working on 3.9 support for the next release.
