### ISSUE TITLE
kubectl diff

### ISSUE THREAD

**Issue by Vad1mo** [trailofbits/graphtage#68]
The diff in Kubectl can be altered with `KUBECTL_EXTERNAL_DIFF ` [here is the ref](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#diff)

This option do all work:

- `KUBECTL_EXTERNAL_DIFF="colordiff -N -u"`
- `KUBECTL_EXTERNAL_DIFF="dyff between --omit-header --set-exit-code"`
- `KUBECTL_EXTERNAL_DIFF='diff -qr'`

I can't, however, make it work with [graphtage](https://github.com/trailofbits/graphtage) using the following config 

 KUBECTL_EXTERNAL_DIFF="graphtage --from-yaml --to-yaml --debug " kubectl diff -f ./dist/aws/cert-manager.k8s.yaml

```
Traceback (most recent call last):
  File "/Users/vadim/.local/bin/graphtage", line 8, in <module>
    sys.exit(main())
  File "/Users/vadim/.local/lib/python3.10/site-packages/graphtage/__main__.py", line 323, in main
    from_tree = from_format.build_tree_handling_errors(from_path, options)
  File "/Users/vadim/.local/lib/python3.10/site-packages/graphtage/yaml.py", line 236, in build_tree_handling_errors
    return self.build_tree(path=path, options=options)
  File "/Users/vadim/.local/lib/python3.10/site-packages/graphtage/yaml.py", line 228, in build_tree
    tree = build_tree(path=path, options=options)
  File "/Users/vadim/.local/lib/python3.10/site-packages/graphtage/yaml.py", line 23, in build_tree
    with open(path, 'rb') as stream:
IsADirectoryError: [Errno 21] Is a directory: '/var/folders/v5/27sfclt13g54_qgh9kmkqf6w0000gn/T/LIVE-3245526907'
```

How could I accomplish that with [graphtage](https://github.com/trailofbits/graphtage)?

**Comment by ESultanik** [comment]
@Vad1mo Status check against master (`9fe0d58`, v0.4.0): still fails, for the reason your traceback shows. Graphtage takes two files, and `kubectl diff` hands its external differ two *directories*.

```console
$ graphtage --no-status --from-yaml --to-yaml dirA dirB
...
  File "graphtage/yaml.py", line 33, in build_tree
    with open(path, 'rb') as stream:
IsADirectoryError: [Errno 21] Is a directory: '.../dirA'
```

There is no `os.path.isdir` check anywhere in the package, and every filetype's `build_tree` calls `open(path)`, so this is the same failure for all formats. Without a MIME override you get a different error instead, `Could not determine the filetype`, because a directory has no extension to guess from. Adding directory support means walking both trees, pairing files by relative path, and deciding what to emit for files present on only one side. That is the work this issue tracks.

One thing that has changed since you filed this, which matters for the tools you compared against: exit codes now follow `diff` conventions. `0` for no differences, `1` for differences found, `2` for an error, `141` for a closed pipe. So the `--set-exit-code` behavior you get from `dyff` is available, once the directory problem is solved.

`graphtage-git-diff` (`graphtage/git.py`) is the shape a `kubectl` wrapper would take. Git invokes an external diff driver once per file, so that entry point handles a single pair of paths and forwards the rest to Graphtage. A `kubectl` wrapper needs the opposite: accept two directories, walk them, and invoke Graphtage per matching pair. That is a small script today if you need it before this issue is fixed.
